# Generated by Django 5.1.5 on 2025-04-07 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='brand',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goods',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goods',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goods',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goods',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goodsdetail',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_set', to='goodsapp.category'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='gdesc',
            field=models.TextField(max_length=100, verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='gname',
            field=models.CharField(max_length=100, unique=True, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodsdetail_set', to='goodsapp.goods'),
        ),
        migrations.AlterField(
            model_name='goodsdetailname',
            name='gdname',
            field=models.CharField(max_length=100, verbose_name='商品详情页中的信息类名'),
        ),
    ]
