# Generated by Django 5.1.5 on 2025-04-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0002_goods_brand_goods_is_hot_goods_is_new_goods_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
