# Generated by Django 5.1.5 on 2025-04-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0003_alter_goods_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='brand_i18n',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='goods',
            name='description_i18n',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='goods',
            name='name_i18n',
            field=models.JSONField(default=dict),
        ),
    ]
