"""
Django settings for crossborder_trade project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import importlib
import os
from pathlib import Path

from crossborder_trade.celery_compat import CELERY_AVAILABLE, crontab

if CELERY_AVAILABLE:
    from kombu import Exchange, Queue
else:  # pragma: no cover - kombu is optional when Celery isn't installed yet
    Exchange = Queue = None

DJANGO_CELERY_BEAT_AVAILABLE = importlib.util.find_spec('django_celery_beat') is not None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name: str, default=False) -> bool:
    return os.getenv(name, str(default)).lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--$dqd5+0q@1px(v65hx!@lkkg7-y@skg9n1@ld9p&kmo3vqi_1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# 修改后端服务的主机地址
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    # app引用
    'userapp.apps.UserappConfig',
    'goodsapp.apps.GoodsappConfig',
    'orderapp.apps.OrderappConfig',
    'cartapp.apps.CartappConfig',
    'paymentapp.apps.PaymentappConfig',
    # 跨域处理
    'corsheaders',
]

if DJANGO_CELERY_BEAT_AVAILABLE:
    INSTALLED_APPS.append('django_celery_beat')

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',  # 临时中间件先注释掉
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 注意必须在这个位置
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

# 允许前端请求网址的配置
CORS_ALLOW_CREDENTIALS = True  # 允许携带cookie信息
CORS_ORIGIN_ALLOW_ALL = True  # 允许所有来源进行跨域请求

# 跨域时，允许在请求头中携带的参数字段
CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Pragma',
    'token'
)

# 对应的发送的请求的跨域
CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)
# 跨域配置结束

# 配置缓存开始
REDIS_CACHE_URL = os.getenv('REDIS_CACHE_URL', os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'))
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
# 配置缓存结束

# 指定自定义用户模型
AUTH_USER_MODEL = 'userapp.UserInfo'  # 添加这行

# JWT配置
from datetime import timedelta

SIMPLE_JWT = {
    # 使用 account 作为 token 的用户标识（与 USERNAME_FIELD 保持一致）
    'USER_ID_FIELD': 'account',  # 修改点：原默认是 'id'
    'USER_ID_CLAIM': 'account',  # token payload 中存储的字段名

    # 登录时使用的字段（对应 authenticate() 的字段名）
    'AUTHENTICATION_BACKENDS': [
        'django.contrib.auth.backends.ModelBackend',
    ],

    # 自定义登录视图字段（允许用 account 代替 username）
    'AUTH_USER_MODEL_USERNAME_FIELD': None,  # 禁用默认 username
    'AUTH_USER_MODEL_ACCOUNT_FIELD': 'account',  # 指定自定义字段

    # TOKEN无效，配置
    'AUTH_HEADER_TYPES': ('Bearer',),
    # Token 有效期配置
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    #
    #     # 改模型时一起改的
    #     'USER_ID_FIELD': 'id',  # 使用自定义模型的ID
    #     # 'USER_ID_CLAIM': 'user_id',
    #     # 'BLACKLIST_AFTER_ROTATION': False  # 禁用token黑名单
    # }
    # SIMPLE_JWT = {
    #     'ROTATE_REFRESH_TOKENS': False,  # 不自动刷新 token
    #     'BLACKLIST_AFTER_ROTATION': False,  # 不记录 token 到黑名单
}
# JWT配置结束
# DRF配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # )
}

ROOT_URLCONF = 'crossborder_trade.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crossborder_trade.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'crossborder_trade',
        'USER': 'root',
        'PASSWORD': '2642',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',  # 支持存储emoji和其他特殊字符
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",  # 设置严格模式
        }
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# 图片路径的配置
# BASE_DIR=os.path.dirname(os.path.abspath(__file__))

STATIC_URL = 'static/'
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 支付环节配置
# 模拟支付配置
MOCK_PAYMENT_SUCCESS_RATE = 0.8  # 模拟支付成功的概率（80%）

# Kafka 默认配置，便于本地开发
KAFKA_BOOTSTRAP_SERVERS = os.getenv('KAFKA_BOOTSTRAP_SERVERS', 'localhost:9092')

# Celery / 异步任务配置
ORDER_EXPIRATION_MINUTES = int(os.getenv('ORDER_EXPIRATION_MINUTES', '30'))

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = os.getenv('CELERY_TIMEZONE', 'UTC')
CELERY_ENABLE_UTC = True

CELERY_BASE_QUEUE = os.getenv('CELERY_DEFAULT_QUEUE', 'default')
CELERY_ORDERS_QUEUE = os.getenv('CELERY_ORDERS_QUEUE', 'orders')
CELERY_PAYMENTS_QUEUE = os.getenv('CELERY_PAYMENTS_QUEUE', 'payments')
CELERY_NOTIFICATIONS_QUEUE = os.getenv('CELERY_NOTIFICATIONS_QUEUE', 'notifications')

CELERY_TASK_DEFAULT_QUEUE = CELERY_BASE_QUEUE
CELERY_TASK_DEFAULT_EXCHANGE = CELERY_BASE_QUEUE
CELERY_TASK_DEFAULT_EXCHANGE_TYPE = 'direct'
CELERY_TASK_DEFAULT_ROUTING_KEY = CELERY_BASE_QUEUE
if CELERY_AVAILABLE and Queue is not None and Exchange is not None:
    CELERY_TASK_QUEUES = (
        Queue(CELERY_BASE_QUEUE, Exchange(CELERY_BASE_QUEUE), routing_key=CELERY_BASE_QUEUE),
        Queue(CELERY_ORDERS_QUEUE, Exchange(CELERY_ORDERS_QUEUE), routing_key=CELERY_ORDERS_QUEUE),
        Queue(CELERY_PAYMENTS_QUEUE, Exchange(CELERY_PAYMENTS_QUEUE), routing_key=CELERY_PAYMENTS_QUEUE),
        Queue(
            CELERY_NOTIFICATIONS_QUEUE,
            Exchange(CELERY_NOTIFICATIONS_QUEUE),
            routing_key=CELERY_NOTIFICATIONS_QUEUE,
        ),
    )
else:  # pragma: no cover - simplifies settings when Celery isn't available yet
    CELERY_TASK_QUEUES = (
        {"name": CELERY_BASE_QUEUE},
        {"name": CELERY_ORDERS_QUEUE},
        {"name": CELERY_PAYMENTS_QUEUE},
        {"name": CELERY_NOTIFICATIONS_QUEUE},
    )
CELERY_TASK_ROUTES = {
    'orderapp.tasks.send_order_confirmation_notification': {
        'queue': CELERY_NOTIFICATIONS_QUEUE,
        'routing_key': CELERY_NOTIFICATIONS_QUEUE,
    },
    'orderapp.tasks.expire_unpaid_orders': {
        'queue': CELERY_ORDERS_QUEUE,
        'routing_key': CELERY_ORDERS_QUEUE,
    },
    'orderapp.tasks.publish_outbox_events': {
        'queue': CELERY_NOTIFICATIONS_QUEUE,
        'routing_key': CELERY_NOTIFICATIONS_QUEUE,
    },
    'paymentapp.tasks.handle_successful_payment': {
        'queue': CELERY_PAYMENTS_QUEUE,
        'routing_key': CELERY_PAYMENTS_QUEUE,
    },
}

CELERY_TASK_ACKS_LATE = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_DEFAULT_RETRY_DELAY = int(os.getenv('CELERY_TASK_DEFAULT_RETRY_DELAY', '30'))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv('CELERY_TASK_SOFT_TIME_LIMIT', '180'))
CELERY_TASK_TIME_LIMIT = int(os.getenv('CELERY_TASK_TIME_LIMIT', '300'))
CELERY_WORKER_CONCURRENCY = int(os.getenv('CELERY_WORKER_CONCURRENCY', '4'))
CELERY_WORKER_PREFETCH_MULTIPLIER = int(os.getenv('CELERY_WORKER_PREFETCH_MULTIPLIER', '1'))
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_ALWAYS_EAGER = env_bool('CELERY_TASK_ALWAYS_EAGER', False)
CELERY_TASK_EAGER_PROPAGATES = env_bool('CELERY_TASK_EAGER_PROPAGATES', True)
CELERY_BEAT_SCHEDULE = {
    'expire-unpaid-orders': {
        'task': 'orderapp.tasks.expire_unpaid_orders',
        'schedule': crontab(minute='*/15'),
        'options': {'queue': CELERY_ORDERS_QUEUE},
    },
    'publish-outbox-events': {
        'task': 'orderapp.tasks.publish_outbox_events',
        'schedule': crontab(minute='*/5'),
        'options': {'queue': CELERY_NOTIFICATIONS_QUEUE},
    },
}
default_celery_scheduler = (
    'django_celery_beat.schedulers:DatabaseScheduler'
    if DJANGO_CELERY_BEAT_AVAILABLE
    else 'celery.beat:PersistentScheduler'
)
CELERY_BEAT_SCHEDULER = os.getenv('CELERY_BEAT_SCHEDULER', default_celery_scheduler)


try:
    from .local_settings import *
except ImportError:
    pass
