# Generated by Django 5.1.5 on 2025-11-03 00:23

import eventstream.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('sent', 'Sent'), ('dead_letter', 'Dead letter')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=eventstream.models.default_max_attempts)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(default=eventstream.models.default_next_attempt_at)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('correlation_id', models.CharField(default=eventstream.models.default_correlation_id, max_length=64)),
                ('idempotency_key', models.CharField(default=eventstream.models.default_idempotency_key, max_length=128, unique=True)),
                ('message_key', models.CharField(blank=True, max_length=128)),
                ('error_type', models.CharField(blank=True, max_length=128)),
                ('error_message', models.TextField(blank=True)),
                ('dead_lettered_at', models.DateTimeField(blank=True, null=True)),
                ('dead_letter_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['state', 'next_attempt_at'], name='event_state_ready_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='event_aggregate_idx'), models.Index(fields=['topic', 'state'], name='event_topic_state_idx')],
            },
        ),
    ]
