# Generated by Django 5.1.5 on 2025-03-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='UserInfo',
            new_name='aUserInfo',
        ),
        migrations.RenameField(
            model_name='realname',
            old_name='UserInfo',
            new_name='rUserInfo',
        ),
    ]
