# Generated by Django 5.1.5 on 2025-03-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_userinfo_address_auserinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=225, verbose_name='密码'),
        ),
    ]
