# Generated by Django 5.1.5 on 2025-03-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_address_auserinfo_alter_realname_ruserinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='UserInfo',
        ),
    ]
