# Generated by Django 5.1.5 on 2025-03-27 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_userinfo_groups_userinfo_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='address',
            name='aUserInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userinfo'),
        ),
        migrations.AlterField(
            model_name='realname',
            name='rUserInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userinfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='account',
            field=models.CharField(max_length=64, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=225, verbose_name='密码'),
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table=None,
        ),
    ]
