# Generated by Django 5.1.5 on 2025-03-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_remove_userinfo_groups_remove_userinfo_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='account',
            field=models.CharField(max_length=64, unique=True, verbose_name='账号'),
        ),
    ]
