# Generated by Django 5.1.5 on 2025-04-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_userinfo_groups_userinfo_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realname',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
