# Generated by Django 5.1.5 on 2025-04-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_realname_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realname',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
