# Generated by Django 5.1.5 on 2025-04-17 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
        ('goodsapp', '0004_goods_brand_i18n_goods_description_i18n_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goodsapp.goods'),
        ),
    ]
