# Generated by Django 5.1.5 on 2025-03-30 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goodsapp', '0001_initial'),
        ('userapp', '0011_userinfo_groups_userinfo_is_superuser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(max_length=50)),
                ('status', models.CharField(default='待支付', max_length=50)),
                ('pay', models.CharField(default='alipay', max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.FloatField(default=0, verbose_name='总金额')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.address')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='价格')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.order')),
            ],
        ),
    ]
