# Generated by Django 5.1.5 on 2025-03-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_num',
            field=models.CharField(default=1, max_length=50, verbose_name='订单号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='trade_no',
            field=models.CharField(max_length=50, verbose_name='交易编号'),
        ),
    ]
